blank_issues_enabled: false
contact_links:
  - name: Soporte
    url: https://github.com/Todointerconectado/basicojavascript/issues/new
    about: Contacta al equipo para soporte o preguntas generales.

issue_templates:
  - name: üêõ Reportar un error
    description: Reporta un problema detectado en el proyecto.
    template: ISSUE_TEMPLATE/bug_report.md
    labels: bug
  - name: ‚ú® Solicitar funci√≥n
    description: Proponer una nueva caracter√≠stica para el proyecto.
    template: ISSUE_TEMPLATE/feature_request.md
    labels: enhancement
  - name: üìö Documentaci√≥n
    description: Sugerir mejoras o correcciones en la documentaci√≥n.
    template: ISSUE_TEMPLATE/documentation.md
    labels: documentation
  - name: ‚ùì Pregunta
    description: Hacer una consulta o pedir aclaraciones sobre el proyecto.
    template: ISSUE_TEMPLATE/question.md
    labels: question
